# Generated by Django 4.1.5 on 2023-01-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeleryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.TextField(blank=True, null=True)),
                ("state", models.TextField(blank=True, null=True)),
                ("args", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
