# Generated by Django 4.1.5 on 2023-01-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celerylog",
            name="args",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="celerylog",
            name="state",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="celerylog",
            name="task_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
