# Generated by Django 4.1.5 on 2023-01-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_celerylog_args_alter_celerylog_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeleryLog2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=50, null=True)),
                ("state", models.CharField(blank=True, max_length=15, null=True)),
                ("args", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
